### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by diegodeodati** [mhvis/samsung-tv-control#1]
Hi,
i have a problem.
When i try to connect to my samsung UE48JU64000:

 java.net.ConnectException: Connection refused: connect

i use 55000 default port

**Comment by mhvis** [comment]
Hello,

> Samsung TV's built in 2014 and later use encryption and can therefore not be controlled by this library!

Via [this page](http://www.samsung.com/uk/support/skp/faq/1052003) you can find out in what year the TV was manufactured. As your TV is manufactured in 2015 it is sadly not supported.
